# Generated by Django 6.0.2 on 2026-02-25 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_merge_20260223_2116'),
        ('tickets', '0012_remove_template_model'),
    ]

    operations = [
    ]
