# Generated by Django 6.0.2 on 2026-02-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_merge_20260225_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='channel_type',
            field=models.CharField(choices=[('admin_employee', 'Admin ↔ Employee')], max_length=20),
        ),
    ]
