# Generated by Django 6.0.2 on 2026-02-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_remove_client_channel_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed'), ('escalated', 'Escalated (Internal)'), ('escalated_external', 'Escalated (External)'), ('pending_closure', 'Pending Closure')], default='open', max_length=20),
        ),
        migrations.DeleteModel(
            name='CSATSurvey',
        ),
    ]
