# Generated by Django 6.0.2 on 2026-04-01 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0037_project_title_hierarchy_and_type_of_service_others_move'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Legacy direct client link (kept for backward compatibility)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='tickets.client'),
        ),
    ]
