# Generated by Django 6.0.2 on 2026-04-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0043_ticket_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='visibility',
            field=models.CharField(choices=[('all', 'All (Supervisors, Technicians & Sales)'), ('admin', 'Supervisors Only'), ('employee', 'Technicians Only'), ('sales', 'Sales Only')], default='all', max_length=20),
        ),
    ]
