# Generated by Django 6.0.2 on 2026-07-24 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0046_product_firmware_and_software_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(default='Service Report', help_text='Main title displayed in the PDF report header.', max_length=255)),
                ('header_company', models.CharField(default='Maptech Information Solutions Inc.', help_text='Company name displayed in the PDF report header.', max_length=255)),
                ('footer_left', models.CharField(default='Maptech Information Solutions Inc.', help_text='Content for the left side of the PDF report footer.', max_length=255)),
                ('footer_right', models.TextField(default='Confidential &mdash; For Authorized Use Only', help_text='Content for the right side of the PDF report footer. Can include HTML.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Settings',
                'verbose_name_plural': 'Report Settings',
            },
        ),
    ]
