# Generated by Django 6.0.2 on 2026-02-26 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_agreed_privacy_policy',
        ),
    ]
