# Generated by Django 6.0.2 on 2026-03-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_recovery_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('employee', 'Employee'),
                    ('sales', 'Sales'),
                    ('admin', 'Admin'),
                    ('superadmin', 'Superadmin'),
                ],
                default='employee',
                max_length=12,
            ),
        ),
    ]
