# Generated by Django 6.0.2 on 2026-04-08

from django.db import migrations, models
from django.contrib.auth.hashers import make_password


def _looks_hashed(value: str) -> bool:
    return '$' in value and len(value.split('$')) >= 3


def hash_existing_recovery_keys(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.exclude(recovery_key='').iterator():
        key = (user.recovery_key or '').strip()
        if key and not _looks_hashed(key):
            user.recovery_key = make_password(key, hasher='pbkdf2_sha256')
            user.save(update_fields=['recovery_key'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_role_add_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='recovery_key',
            field=models.CharField(
                max_length=255,
                db_index=True,
                blank=True,
                help_text='Hashed recovery key for password reset verification.',
            ),
        ),
        migrations.RunPython(hash_existing_recovery_keys, migrations.RunPython.noop),
    ]
